### ISSUE TITLE
Error Make.sh

### ISSUE THREAD

**Issue by Jonas4pp** [BobHasNoSoul/jellyfin-featured#7]
Very good, dear.

I want to congratulate you for the ability and effort you have shown in this interesting project. I am really impressed by your work.

Tried to deploy it on my private server, but encountered a slight snag while running the make.sh script.

make.sh: line 2: $'\r': command not found
make.sh: line 8: $'\r': command not found
make.sh: line 9: $'\r': command not found
make.sh: line 10: syntax error near unexpected token `$'{\r''
'ake.sh: line 10: `get_item_description() {

**Comment by BobHasNoSoul** [comment]
can you confirm what operating system you are running?

can confirm the script works on ubuntu server

**Comment by ashipaek0** [comment]
I have this same error on Ubuntu server 24.04

Cloned the git directly into my home directory and edited the files to add UserID and apikey

```
$ sudo bash ./make.sh -p -l userfavorites.txt -h "Spotlight"
./make.sh: line 2: $'\r': command not found
./make.sh: line 8: $'\r': command not found
./make.sh: line 9: $'\r': command not found
./make.sh: line 10: syntax error near unexpected token `$'{\r''
```

**Comment by Jonas4pp** [comment]
Hello friends, the truth is I still have the same problem so I decided not to break my head anymore and use the alternative version and it works great for me.
![Captura de pantalla 2024-06-27 071222](https://github.com/BobHasNoSoul/jellyfin-featured/assets/35243274/a5435bd7-e1e2-4214-9a00-aa59bd30cddb)

**Comment by BobHasNoSoul** [comment]
please see the updated make.sh it fixed the bash error

if issue still persists run the command `sudo bash ./make.sh` followed by your extra configs
