### ISSUE TITLE
Spotlight showing on favorites tab

### ISSUE THREAD

**Issue by sureshfizzy** [BobHasNoSoul/jellyfin-featured#8]
Hi, first of all thanks for these mods, it looks great!! I am facing a issue on favorites tab, I have configured spotlight using the alternative method (slideshow.html) and now I can see spotlight tab on favorites. Due to this, my favourites list are hidden. Attached the pic below.

Jellyfin version: 10.9.8
OS: Ubuntu 22.04

![Screenshot_2024-07-30-23-18-30-47_4b95a63cd60fd3e0f30739d89812bf6c](https://github.com/user-attachments/assets/67fa69bc-8ed5-4a16-a464-834c4fb021bf)

**Comment by BobHasNoSoul** [comment]
You're welcome I'm glad you found it useful, that's a new one, I have not
encountered a favourites bug that stops it from showing i do know it loads
above the favorites items. Can you check your inspect options and look for
errors in the log when you reload the page in your browser (chrome or
firefox developer console is usually decent at this)

**Comment by sureshfizzy** [comment]
When i do inspect, i see few errors..

<img width="385" alt="image" src="https://github.com/user-attachments/assets/09582713-41f8-4d5a-b36c-2af4b77c95df">

<img width="394" alt="image" src="https://github.com/user-attachments/assets/8da099ac-077a-453c-9316-f782391c143c">

**Comment by BobHasNoSoul** [comment]
Okay so the first one is an error because there isn't a logo for an item(s)
(this is just saying that logo is missing)

The second is a new one.. can you try the following and tell me the result

Create a new user account (or use any other account) favourite one movie
one TV show etc (just to create the list in category's)

Then go to the favorites tab and confirm they load

**Comment by MilkFlix** [comment]
It's probably because it's trying to fetch a media number that's greater
than the number of items. Try setting the max media variable lower.

**Comment by MakD** [comment]
+1 can replicate the same

**Comment by BobHasNoSoul** [comment]
Updated install instructions can you try the install method using slideshow.html from the repo and using the updated instructions

**Comment by sureshfizzy** [comment]
@BobHasNoSoul thanks for fixing it, sorry was been away with some works so couldn't check this out earlier
